---
# tasks file for iis

- name: install xWebAdministration module
  win_psmodule:
    name: xWebAdministration
    state: present

- name: install IIS features that are required
  win_dsc:
    resource_name: WindowsFeature
    Name: '{{item}}'
    Ensure: Present
  with_items:
  - Web-Server
  - Web-Asp-Net45
  
- name: install .NET Framework 3.5
  win_dsc:
    resource_name: WindowsFeature
    Name: '{{item}}'
    Ensure: Present
    IncludeAllSubFeature: True 
  with_items:
  - NET-Framework-Features

- name: setup web content
  win_dsc:
    resource_name: File
    DestinationPath: C:\inetpub\IISSite\index.html
    Type: File
    Contents: |
      <html>
      <head><title>IIS Site</title></head>
      <body>This is the body</body>
      </html>
    Ensure: present
    
- name: create new website
  win_dsc:
    resource_name: xWebsite
    Name: NewIISSite
    State: Started
    PhysicalPath: C:\inetpub\IISSite\
    BindingInfo:
 #   - Protocol: https
 #     Port: 8443
 #     CertificateStoreName: My
 #     CertificateThumbprint: C676A89018C4D5902353545343634F35E6B3A659
 #     HostName: DSCTest
 #     IPAddress: '*'
 #     SSLFlags: 1
    - Protocol: http
      Port: 8080
      IPAddress: '*'
    AuthenticationInfo:
      Anonymous: no
      Basic: yes
      Digest: no
      Windows: yes
- name: Simple GET operation
  aws_s3:
    bucket: tmk-wcl01
    object: /tmk-wcl01/Notepad%2B%2B+v7.5.5.msi
    dest: C:\Users\Administrator\
    mode: get
